### ISSUE TITLE
about | ToMoToes

### ISSUE THREAD

**Issue by JinmaQAQ** [JinmaQAQ/JinmaQAQ.github.io#18]
https://tomotoes.com/about/ 

 关于ToMoToes：一个坏掉的番茄首先，这是一个悲惨的故事，经过 建站以来 一个月的域名挑选，我已明确锁定了两个十分高雅的域名：  wozuiniubi.com youaredog.com    但在买域名的前一天 (2017.11.12) 本人搜到了 tomotoes这个神奇的域名！ 哇，激动！番茄欸！额，现在看来，mdzz。。。 随后和低智商并且在学语言的她商量，她立即否决了 我前两个蓄谋已

**Comment by lliullin** [comment]
占楼

**Comment by JinmaQAQ** [comment]
> @lliullin
> 占楼

测试

**Comment by JinmaQAQ** [comment]
> @lliullin
> 占楼

huifu
